[package]
name = "str-ext"
version = "0.2.0"
authors = ["Author <email@provider.com>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[lib]
crate-type = ["cdylib", "staticlib"]
bench = false

[dependencies]
janetrs = "0.3.1"
